### ISSUE TITLE
Version 1.0.6 is missing dist folder

### ISSUE THREAD

**Issue by expobrain** [bvaughn/react-highlight.js#10]
The latest version 1.0.6 is missing the `dist/main.js` file pointed by the `main` key in `package.json`

**Comment by bvaughn** [comment]
You're correct. Looks like something went wrong with the most recent release. Sorry for the inconvenience. I've deprecated it and re-published as `react-highlight.js@1.0.7`. Hope this release works better for you.

**Comment by expobrain** [comment]
yes, 1.0.7 is working correctly, Thank you!
