### ISSUE TITLE
Tagging a release for 1.0.7?

### ISSUE THREAD

**Issue by danielcompton** [bvaughn/react-highlight.js#11]
We use this library in [cljsjs](https://github.com/cljsjs/packages/tree/master/react-highlight), a system for packaging JavaScript packages for ClojureScript. To build a release we need to have a tagged version to download. Would it be possible for you to tag the 1.0.7 release so we can use it?

Thanks!

**Comment by bvaughn** [comment]
Just, I just pushed a 1.0.7 tag

**Comment by danielcompton** [comment]
Thanks!
